### ISSUE TITLE
1.0.1 fails to compile with 1.40.0-nightly (6767d9b90 2019-10-11)

### ISSUE THREAD

**Issue by kdy1** [dtolnay/ryu#17]
- https://travis-ci.com/swc-project/node-swc/jobs/244953228#L210-L212
 - https://ci.appveyor.com/project/kdy1/node-swc/builds/28058332#L20

Error message:
```
error[E0658]: use of unstable library feature 'maybe_uninit'
 --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/buffer/mod.rs:4:5
  |
4 | use core::mem::MaybeUninit;
  |     ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/53491
  = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/buffer/mod.rs:27:13
   |
27 |     bytes: [MaybeUninit<u8>; 24],
   |             ^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53491
   = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/buffer/mod.rs:41:30
   |
41 |         let bytes = unsafe { MaybeUninit::uninit().assume_init() };
   |                              ^^^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53491
   = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:24:5
   |
24 | use core::mem::MaybeUninit;
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53491
   = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:196:43
    |
196 |     let mut vp_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
    |                                           ^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:196:24
    |
196 |     let mut vp_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
    |                        ^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:198:43
    |
198 |     let mut vm_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
    |                                           ^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:198:24
    |
198 |     let mut vm_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
    |                        ^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/buffer/mod.rs:41:52
   |
41 |         let bytes = unsafe { MaybeUninit::uninit().assume_init() };
   |                                                    ^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53491
   = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/buffer/mod.rs:100:23
    |
100 |         self.bytes[0].as_ptr()
    |                       ^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/buffer/mod.rs:112:23
    |
112 |         self.bytes[0].as_mut_ptr()
    |                       ^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:222:25
    |
222 |             { vp_uninit.as_mut_ptr() },
    |                         ^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:226:25
    |
226 |             { vm_uninit.as_mut_ptr() },
    |                         ^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:233:37
    |
233 |             vp = unsafe { vp_uninit.assume_init() };
    |                                     ^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:234:37
    |
234 |             vm = unsafe { vm_uninit.assume_init() };
    |                                     ^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:273:25
    |
273 |             { vp_uninit.as_mut_ptr() },
    |                         ^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:277:25
    |
277 |             { vm_uninit.as_mut_ptr() },
    |                         ^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:284:37
    |
284 |             vp = unsafe { vp_uninit.assume_init() };
    |                                     ^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'maybe_uninit'
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:285:37
    |
285 |             vm = unsafe { vm_uninit.assume_init() };
    |                                     ^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53491
    = help: add #![feature(maybe_uninit)] to the crate attributes to enable
```

**Comment by dtolnay** [comment]
That error is not from 1.40.0-nightly, since MaybeUninit was stabilized in Rust 1.36.0.

```console
$ rustup update nightly-2019-10-12

$ rustc +nightly-2019-10-12 --version
rustc 1.40.0-nightly (6767d9b90 2019-10-11)

$ cargo +nightly-2019-10-12 build
   Compiling ryu v1.0.1 (/git/ryu)
    Finished dev [unoptimized + debuginfo] target(s) in 0.58s
```

If it's from an older nightly -- we don't support old nightlies in general. With nightly the expectation is that you are upgrading the compiler every night if you are pulling in library updates.
